from typing import List


def heroe_valido(heroe: str) -> bool:
    lista_heroes: List[str] = [
        "abaddon",
        "alchemist",
        "ancient apparition",
        "anti-mage",
        "arc warden",
        "axe",
        "bane",
        "batrider",
        "beastmaster",
        "bloodseeker",
        "bounty hunter",
        "brewmaster",
        "bristleback",
        "broodmother",
        "centaur warrunner",
        "chaos knight",
        "chen",
        "clinkz",
        "clockwerk",
        "crystal maiden",
        "dark seer",
        "dark willow",
        "dawnbreaker",
        "dazzle",
        "death prophet",
        "disruptor",
        "doom",
        "dragon knight",
        "drow ranger",
        "earth spirit",
        "earthshaker",
        "elder titan",
        "ember spirit",
        "enchantress",
        "enigma",
        "faceless void",
        "grimstroke",
        "gyrocopter",
        "hoodwink",
        "huskar",
        "invoker",
        "io",
        "jakiro",
        "juggernaut",
        "keeper of the light",
        "kunkka",
        "legion commander",
        "leshrac",
        "lich",
        "lifestealer",
        "lina",
        "lion",
        "lone druid",
        "luna",
        "lycan",
        "magnus",
        "marci",
        "mars",
        "medusa",
        "meepo",
        "mirana",
        "monkey king",
        "morphling",
        "muerta",
        "naga siren",
        "natures prophet",
        "necrophos",
        "night stalker",
        "nyx assassin",
        "ogre magi",
        "omniknight",
        "oracle",
        "outworld destroyer",
        "pangolier",
        "phantom assassin",
        "phantom lancer",
        "phoenix",
        "primal beast",
        "puck",
        "pudge",
        "pugna",
        "queen of pain",
        "razor",
        "riki",
        "rubick",
        "sand king",
        "shadow demon",
        "shadow fiend",
        "shadow shaman",
        "silencer",
        "skywrath mage",
        "slardar",
        "slark",
        "snapfire",
        "sniper",
        "spectre",
        "spirit breaker",
        "storm spirit",
        "sven",
        "techies",
        "templar assassin",
        "terrorblade",
        "tidehunter",
        "timbersaw",
        "tinker",
        "tiny",
        "treant protector",
        "troll warlord",
        "tusk",
        "underlord",
        "undying",
        "ursa",
        "vengeful spirit",
        "venomancer",
        "viper",
        "visage",
        "void spirit",
        "warlock",
        "weaver",
        "windranger",
        "winter wyvern",
        "witch doctor",
        "wraith king",
        "zeus",
    ]

    if heroe in lista_heroes:
        return True
    else:
        raise ValueError("El nombre del héroe no es válido.")
